// API Registry — 167 APIs organized for the 25-agent trading system
// Categories: Finance (58), Cryptocurrency (63), Data Access (46)

export interface ApiEntry {
  id: number;
  name: string;
  category: "Finance" | "Cryptocurrency" | "Data_Access";
  description: string;
  auth: "No" | "apiKey" | "OAuth";
  url: string;
  docs: string;
  status: "connected" | "available" | "needs_key" | "premium";
  priority: "critical" | "high" | "medium" | "low";
  usedBy: string[];
}

export const API_REGISTRY: ApiEntry[] = [
  // ============================================================
  // FINANCE (IDs 1–58)
  // ============================================================
  {
    id: 1,
    name: "bunq",
    category: "Finance",
    description: "Open bank RESTful API",
    auth: "OAuth",
    url: "https://www.bunq.com",
    docs: "https://doc.bunq.com/",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 2,
    name: "Baremetrics",
    category: "Finance",
    description: "Payment analytics and insights",
    auth: "apiKey",
    url: "https://baremetrics.com",
    docs: "https://developers.baremetrics.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 3,
    name: "Mono",
    category: "Finance",
    description: "Bank accounts and transactions in Africa",
    auth: "apiKey",
    url: "https://mono.co",
    docs: "https://docs.mono.co/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 4,
    name: "Finnhub Stock API",
    category: "Finance",
    description: "Real-time stock data, financials, and alternative data",
    auth: "apiKey",
    url: "https://finnhub.io",
    docs: "https://finnhub.io/docs/api",
    status: "needs_key",
    priority: "high",
    usedBy: ["Macro Analyst", "ML Agent", "Trend Agent"],
  },
  {
    id: 5,
    name: "Boleto.Cloud",
    category: "Finance",
    description: "Brazil boleto generation and management",
    auth: "apiKey",
    url: "https://boleto.cloud",
    docs: "https://boleto.cloud/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 6,
    name: "World Trading Data",
    category: "Finance",
    description: "Real-time and historical market data",
    auth: "apiKey",
    url: "https://www.worldtradingdata.com",
    docs: "https://www.worldtradingdata.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Macro Analyst"],
  },
  {
    id: 7,
    name: "CoinDesk (Finance)",
    category: "Finance",
    description: "Bitcoin Price Index and crypto news",
    auth: "No",
    url: "https://www.coindesk.com",
    docs: "https://www.coindesk.com/coindesk-api",
    status: "connected",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent", "Sentiment Agent"],
  },
  {
    id: 8,
    name: "IEX",
    category: "Finance",
    description: "Stocks and market data",
    auth: "apiKey",
    url: "https://iextrading.com",
    docs: "https://iexcloud.io/docs/api/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Macro Analyst"],
  },
  {
    id: 9,
    name: "Plaid",
    category: "Finance",
    description: "Bank account connections and financial data",
    auth: "apiKey",
    url: "https://plaid.com",
    docs: "https://plaid.com/docs/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Portfolio Manager", "Risk Manager"],
  },
  {
    id: 10,
    name: "CryptoCompare (Finance)",
    category: "Finance",
    description: "Cryptocurrency comparison and market data",
    auth: "apiKey",
    url: "https://www.cryptocompare.com",
    docs: "https://min-api.cryptocompare.com/documentation",
    status: "needs_key",
    priority: "high",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent"],
  },
  {
    id: 11,
    name: "Finage",
    category: "Finance",
    description: "Real-time stock, forex, and crypto data",
    auth: "apiKey",
    url: "https://finage.co.uk",
    docs: "https://finage.co.uk/docs/api",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Momentum Agent"],
  },
  {
    id: 12,
    name: "Hotstoks",
    category: "Finance",
    description: "Stock market data with SQL-like queries",
    auth: "apiKey",
    url: "https://hotstoks.com",
    docs: "https://hotstoks.com/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 13,
    name: "Tradier",
    category: "Finance",
    description: "US equity and option data and trading",
    auth: "apiKey",
    url: "https://tradier.com",
    docs: "https://documentation.tradier.com/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent", "Trend Agent"],
  },
  {
    id: 14,
    name: "PayRequest",
    category: "Finance",
    description: "Payment link generation",
    auth: "apiKey",
    url: "https://payrequest.io",
    docs: "https://payrequest.io/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 15,
    name: "Yahoo Finance",
    category: "Finance",
    description: "Comprehensive market data and financial news",
    auth: "apiKey",
    url: "https://finance.yahoo.com",
    docs: "https://www.yahoofinanceapi.com/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "Macro Analyst", "ML Agent", "Risk Manager"],
  },
  {
    id: 16,
    name: "Tax Data API",
    category: "Finance",
    description: "VAT number validation and tax data",
    auth: "apiKey",
    url: "https://apilayer.com",
    docs: "https://apilayer.com/marketplace/tax_data-api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 17,
    name: "FRED",
    category: "Finance",
    description: "Federal Reserve Economic Data for macro analysis",
    auth: "apiKey",
    url: "https://fred.stlouisfed.org",
    docs: "https://fred.stlouisfed.org/docs/api/fred/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Macro Analyst", "Risk Manager", "Portfolio Manager", "ML Agent"],
  },
  {
    id: 18,
    name: "Aletheia",
    category: "Finance",
    description: "Insider trading data and SEC filings",
    auth: "apiKey",
    url: "https://aletheiaapi.com",
    docs: "https://aletheiaapi.com/docs/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Sentiment Agent", "Research Agent", "Risk Manager"],
  },
  {
    id: 19,
    name: "Citi",
    category: "Finance",
    description: "Citigroup banking and financial APIs",
    auth: "OAuth",
    url: "https://www.citibank.com",
    docs: "https://sandbox.developerhub.citi.com/",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 20,
    name: "Bank Data API",
    category: "Finance",
    description: "IBAN and SWIFT code validation",
    auth: "apiKey",
    url: "https://apilayer.com",
    docs: "https://apilayer.com/marketplace/bank_data-api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 21,
    name: "Econdb",
    category: "Finance",
    description: "Global macroeconomic data and indicators",
    auth: "apiKey",
    url: "https://www.econdb.com",
    docs: "https://www.econdb.com/api/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Macro Analyst", "Risk Manager", "ML Agent"],
  },
  {
    id: 22,
    name: "Polygon",
    category: "Finance",
    description: "Historical and real-time stock market data",
    auth: "apiKey",
    url: "https://polygon.io",
    docs: "https://polygon.io/docs/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "ML Agent", "Macro Analyst"],
  },
  {
    id: 23,
    name: "Banco do Brasil",
    category: "Finance",
    description: "Brazil banking services",
    auth: "OAuth",
    url: "https://www.bb.com.br",
    docs: "https://developers.bb.com.br/",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 24,
    name: "OpenFIGI",
    category: "Finance",
    description: "Financial Instrument Global Identifier from Bloomberg",
    auth: "apiKey",
    url: "https://www.openfigi.com",
    docs: "https://www.openfigi.com/api",
    status: "needs_key",
    priority: "high",
    usedBy: ["Research Agent", "Macro Analyst", "Portfolio Manager"],
  },
  {
    id: 25,
    name: "Square",
    category: "Finance",
    description: "Payment processing and commerce",
    auth: "OAuth",
    url: "https://squareup.com",
    docs: "https://developer.squareup.com/docs",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 26,
    name: "Viafintech",
    category: "Finance",
    description: "Cash payment slips and retail payments",
    auth: "apiKey",
    url: "https://www.viafintech.com",
    docs: "https://docs.viafintech.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 27,
    name: "Fed Treasury",
    category: "Finance",
    description: "US Treasury fiscal and debt data",
    auth: "No",
    url: "https://fiscaldata.treasury.gov",
    docs: "https://fiscaldata.treasury.gov/api-documentation/",
    status: "connected",
    priority: "critical",
    usedBy: ["Macro Analyst", "Risk Manager", "Portfolio Manager"],
  },
  {
    id: 28,
    name: "Nordigen",
    category: "Finance",
    description: "Open banking and bank account APIs",
    auth: "apiKey",
    url: "https://nordigen.com",
    docs: "https://ob.nordigen.com/api/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 29,
    name: "Moov",
    category: "Finance",
    description: "Send, receive, and store money",
    auth: "apiKey",
    url: "https://moov.io",
    docs: "https://docs.moov.io/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 30,
    name: "IG Labs",
    category: "Finance",
    description: "CFD trading and market data",
    auth: "apiKey",
    url: "https://labs.ig.com",
    docs: "https://labs.ig.com/rest-trading-api-reference",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Trend Agent", "Arbitrage Agent"],
  },
  {
    id: 31,
    name: "StockData",
    category: "Finance",
    description: "Real-time market data and financial news",
    auth: "apiKey",
    url: "https://www.stockdata.org",
    docs: "https://www.stockdata.org/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "News Intelligence Agent"],
  },
  {
    id: 32,
    name: "IEX Cloud",
    category: "Finance",
    description: "Comprehensive realtime and historical stock data",
    auth: "apiKey",
    url: "https://iexcloud.io",
    docs: "https://iexcloud.io/docs/api/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Macro Analyst"],
  },
  {
    id: 33,
    name: "Portfolio Optimizer",
    category: "Finance",
    description: "Portfolio analysis and optimization tools",
    auth: "No",
    url: "https://portfoliooptimizer.io",
    docs: "https://docs.portfoliooptimizer.io/",
    status: "connected",
    priority: "critical",
    usedBy: ["Portfolio Manager", "Risk Manager", "ML Agent"],
  },
  {
    id: 34,
    name: "Braintree",
    category: "Finance",
    description: "Online payment processing",
    auth: "OAuth",
    url: "https://www.braintreepayments.com",
    docs: "https://developer.paypal.com/braintree/docs",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 35,
    name: "Stripe API",
    category: "Finance",
    description: "Online payment processing platform",
    auth: "apiKey",
    url: "https://stripe.com",
    docs: "https://stripe.com/docs/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 36,
    name: "Financial Modeling Prep",
    category: "Finance",
    description: "Financial statements, ratios, and fundamentals",
    auth: "apiKey",
    url: "https://financialmodelingprep.com",
    docs: "https://site.financialmodelingprep.com/developer/docs",
    status: "needs_key",
    priority: "high",
    usedBy: ["Macro Analyst", "Research Agent", "ML Agent"],
  },
  {
    id: 37,
    name: "apilayer marketstack",
    category: "Finance",
    description: "Real-time and historical market data",
    auth: "apiKey",
    url: "https://marketstack.com",
    docs: "https://marketstack.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Macro Analyst"],
  },
  {
    id: 38,
    name: "Binlist",
    category: "Finance",
    description: "Bank Identification Number (BIN) database",
    auth: "No",
    url: "https://binlist.net",
    docs: "https://binlist.net/",
    status: "available",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 39,
    name: "MercadoPago",
    category: "Finance",
    description: "Payments platform for Latin America",
    auth: "OAuth",
    url: "https://www.mercadopago.com",
    docs: "https://www.mercadopago.com.br/developers/",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 40,
    name: "Intrinio",
    category: "Finance",
    description: "Comprehensive financial data feeds",
    auth: "apiKey",
    url: "https://intrinio.com",
    docs: "https://docs.intrinio.com/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Macro Analyst", "ML Agent", "Research Agent"],
  },
  {
    id: 41,
    name: "Mastercard",
    category: "Finance",
    description: "Payment solutions and data services",
    auth: "OAuth",
    url: "https://developer.mastercard.com",
    docs: "https://developer.mastercard.com/apis",
    status: "premium",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 42,
    name: "Klarna",
    category: "Finance",
    description: "Buy now, pay later and payment solutions",
    auth: "apiKey",
    url: "https://www.klarna.com",
    docs: "https://docs.klarna.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 43,
    name: "Styvio",
    category: "Finance",
    description: "Stock data and market sentiment analysis",
    auth: "apiKey",
    url: "https://styvio.com",
    docs: "https://styvio.com/docs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Sentiment Agent", "Trend Agent"],
  },
  {
    id: 44,
    name: "Kite Connect",
    category: "Finance",
    description: "Indian stock market trading platform",
    auth: "apiKey",
    url: "https://kite.zerodha.com",
    docs: "https://kite.trade/docs/connect/v3/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent", "Trend Agent"],
  },
  {
    id: 45,
    name: "YNAB",
    category: "Finance",
    description: "Personal budgeting and finance tracking",
    auth: "apiKey",
    url: "https://www.ynab.com",
    docs: "https://api.ynab.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 46,
    name: "Razorpay IFSC",
    category: "Finance",
    description: "Indian bank IFSC code lookup",
    auth: "No",
    url: "https://razorpay.com",
    docs: "https://ifsc.razorpay.com/",
    status: "available",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 47,
    name: "SmartAPI",
    category: "Finance",
    description: "Indian broking and trading services",
    auth: "apiKey",
    url: "https://smartapi.angelbroking.com",
    docs: "https://smartapi.angelbroking.com/docs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent"],
  },
  {
    id: 48,
    name: "Alpha Vantage",
    category: "Finance",
    description: "Stock, forex, and crypto data with technical indicators",
    auth: "apiKey",
    url: "https://www.alphavantage.co",
    docs: "https://www.alphavantage.co/documentation/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "ML Agent", "Macro Analyst", "Risk Manager"],
  },
  {
    id: 49,
    name: "CoinMarketCap",
    category: "Finance",
    description: "Cryptocurrency prices, market cap, and rankings",
    auth: "apiKey",
    url: "https://coinmarketcap.com",
    docs: "https://coinmarketcap.com/api/documentation/v1/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent", "Portfolio Manager"],
  },
  {
    id: 50,
    name: "WallstreetBets",
    category: "Finance",
    description: "Reddit WallStreetBets sentiment and trends",
    auth: "No",
    url: "https://dashboard.nbshare.io/apps/reddit/api/",
    docs: "https://dashboard.nbshare.io/apps/reddit/api/",
    status: "connected",
    priority: "high",
    usedBy: ["Sentiment Agent", "News Intelligence Agent"],
  },
  {
    id: 51,
    name: "Alpaca",
    category: "Finance",
    description: "Commission-free US equity trading API",
    auth: "apiKey",
    url: "https://alpaca.markets",
    docs: "https://alpaca.markets/docs/api-documentation/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Portfolio Manager"],
  },
  {
    id: 52,
    name: "Twelve Data",
    category: "Finance",
    description: "Real-time and historical market data",
    auth: "apiKey",
    url: "https://twelvedata.com",
    docs: "https://twelvedata.com/docs",
    status: "needs_key",
    priority: "high",
    usedBy: ["Trend Agent", "Momentum Agent", "ML Agent"],
  },
  {
    id: 53,
    name: "SEC EDGAR",
    category: "Finance",
    description: "Public company reports and SEC filings",
    auth: "No",
    url: "https://www.sec.gov/edgar",
    docs: "https://www.sec.gov/edgar/sec-api-documentation",
    status: "connected",
    priority: "critical",
    usedBy: ["Risk Manager", "Research Agent", "Macro Analyst"],
  },
  {
    id: 54,
    name: "Barchart",
    category: "Finance",
    description: "Market data and trading solutions",
    auth: "apiKey",
    url: "https://www.barchart.com",
    docs: "https://www.barchart.com/ondemand/api",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Macro Analyst"],
  },
  {
    id: 55,
    name: "Billplz",
    category: "Finance",
    description: "Malaysian payment platform",
    auth: "apiKey",
    url: "https://www.billplz.com",
    docs: "https://www.billplz.com/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Portfolio Manager"],
  },
  {
    id: 56,
    name: "ParityVend",
    category: "Finance",
    description: "Purchasing power parity pricing data",
    auth: "apiKey",
    url: "https://www.parityvend.com",
    docs: "https://www.parityvend.com/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Macro Analyst"],
  },
  {
    id: 57,
    name: "DolarAPI",
    category: "Finance",
    description: "Latin American foreign exchange rates",
    auth: "No",
    url: "https://dolarapi.com",
    docs: "https://dolarapi.com/docs/",
    status: "available",
    priority: "medium",
    usedBy: ["Macro Analyst", "Arbitrage Agent"],
  },
  {
    id: 58,
    name: "Earnings Feed",
    category: "Finance",
    description: "SEC filings, insider trades, and earnings data",
    auth: "apiKey",
    url: "https://earningsfeed.com",
    docs: "https://earningsfeed.com/api/docs",
    status: "needs_key",
    priority: "high",
    usedBy: ["Sentiment Agent", "Research Agent", "Macro Analyst"],
  },

  // ============================================================
  // CRYPTOCURRENCY (IDs 59–120)
  // ============================================================
  {
    id: 59,
    name: "Gemini",
    category: "Cryptocurrency",
    description: "Gemini exchange trading and market data",
    auth: "apiKey",
    url: "https://www.gemini.com",
    docs: "https://docs.gemini.com/rest-api/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 60,
    name: "MercadoBitcoin",
    category: "Cryptocurrency",
    description: "Brazilian cryptocurrency exchange",
    auth: "No",
    url: "https://www.mercadobitcoin.com.br",
    docs: "https://www.mercadobitcoin.com.br/api-doc/",
    status: "available",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 61,
    name: "Block",
    category: "Cryptocurrency",
    description: "Bitcoin payment processing",
    auth: "apiKey",
    url: "https://block.io",
    docs: "https://block.io/api",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent"],
  },
  {
    id: 62,
    name: "Bittrex",
    category: "Cryptocurrency",
    description: "Cryptocurrency exchange trading",
    auth: "apiKey",
    url: "https://bittrex.com",
    docs: "https://bittrex.github.io/api/v3",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 63,
    name: "Bitfinex",
    category: "Cryptocurrency",
    description: "Full-featured crypto trading platform",
    auth: "apiKey",
    url: "https://www.bitfinex.com",
    docs: "https://docs.bitfinex.com/docs",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent", "Trend Agent"],
  },
  {
    id: 64,
    name: "Coinigy",
    category: "Cryptocurrency",
    description: "Multi-exchange portfolio and trading",
    auth: "apiKey",
    url: "https://www.coinigy.com",
    docs: "https://coinigy.docs.apiary.io/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Portfolio Manager", "Arbitrage Agent"],
  },
  {
    id: 65,
    name: "CoinDesk (Crypto)",
    category: "Cryptocurrency",
    description: "Bitcoin price data and news",
    auth: "No",
    url: "https://www.coindesk.com",
    docs: "https://www.coindesk.com/coindesk-api",
    status: "connected",
    priority: "medium",
    usedBy: ["Trend Agent", "Momentum Agent"],
  },
  {
    id: 66,
    name: "Nexchange",
    category: "Cryptocurrency",
    description: "Automated cryptocurrency exchange",
    auth: "No",
    url: "https://nexchange.io",
    docs: "https://nexchange2.docs.apiary.io/",
    status: "available",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 67,
    name: "Kraken",
    category: "Cryptocurrency",
    description: "Major cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.kraken.com",
    docs: "https://docs.kraken.com/rest/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent", "Trend Agent"],
  },
  {
    id: 68,
    name: "FTX",
    category: "Cryptocurrency",
    description: "Crypto derivatives and spot exchange",
    auth: "apiKey",
    url: "https://ftx.com",
    docs: "https://docs.ftx.com/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 69,
    name: "icy.tools",
    category: "Cryptocurrency",
    description: "NFT market data and analytics",
    auth: "apiKey",
    url: "https://icy.tools",
    docs: "https://developers.icy.tools/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 70,
    name: "1inch",
    category: "Cryptocurrency",
    description: "DEX aggregator for best swap rates",
    auth: "No",
    url: "https://1inch.io",
    docs: "https://docs.1inch.io/",
    status: "connected",
    priority: "high",
    usedBy: ["DeFi Agent", "Arbitrage Agent", "Execution Agent"],
  },
  {
    id: 71,
    name: "0x",
    category: "Cryptocurrency",
    description: "DEX token and liquidity pool statistics",
    auth: "apiKey",
    url: "https://0x.org",
    docs: "https://docs.0x.org/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["DeFi Agent", "Arbitrage Agent"],
  },
  {
    id: 72,
    name: "blockfrost Cardano",
    category: "Cryptocurrency",
    description: "Cardano blockchain data access",
    auth: "apiKey",
    url: "https://blockfrost.io",
    docs: "https://docs.blockfrost.io/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["On-Chain Agent", "DeFi Agent"],
  },
  {
    id: 73,
    name: "Mempool",
    category: "Cryptocurrency",
    description: "Bitcoin mempool and fee estimation",
    auth: "No",
    url: "https://mempool.space",
    docs: "https://mempool.space/docs/api/rest",
    status: "connected",
    priority: "high",
    usedBy: ["On-Chain Agent", "Cost Agent", "Execution Agent"],
  },
  {
    id: 74,
    name: "NovaDax",
    category: "Cryptocurrency",
    description: "Cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.novadax.com.br",
    docs: "https://doc.novadax.com/en-US/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 75,
    name: "CryptAPI",
    category: "Cryptocurrency",
    description: "Cryptocurrency payment processing",
    auth: "No",
    url: "https://cryptapi.io",
    docs: "https://docs.cryptapi.io/",
    status: "available",
    priority: "low",
    usedBy: ["Execution Agent"],
  },
  {
    id: 76,
    name: "Bitcambio",
    category: "Cryptocurrency",
    description: "Brazilian crypto exchange",
    auth: "No",
    url: "https://bitcambio.com.br",
    docs: "https://bitcambio.com.br/api",
    status: "available",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 77,
    name: "Binance",
    category: "Cryptocurrency",
    description: "World's largest cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.binance.com",
    docs: "https://binance-docs.github.io/apidocs/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent", "Trend Agent", "Momentum Agent"],
  },
  {
    id: 78,
    name: "ICObench",
    category: "Cryptocurrency",
    description: "ICO ratings and data",
    auth: "apiKey",
    url: "https://icobench.com",
    docs: "https://icobench.com/developers",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 79,
    name: "Coinlore",
    category: "Cryptocurrency",
    description: "Cryptocurrency prices and trading volume",
    auth: "No",
    url: "https://www.coinlore.com",
    docs: "https://www.coinlore.com/cryptocurrency-data-api",
    status: "connected",
    priority: "medium",
    usedBy: ["Trend Agent", "Momentum Agent"],
  },
  {
    id: 80,
    name: "Coinbase",
    category: "Cryptocurrency",
    description: "Major cryptocurrency exchange and wallet",
    auth: "apiKey",
    url: "https://www.coinbase.com",
    docs: "https://docs.cloud.coinbase.com/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent", "Portfolio Manager"],
  },
  {
    id: 81,
    name: "CoinAPI",
    category: "Cryptocurrency",
    description: "Unified API for all cryptocurrency exchanges",
    auth: "apiKey",
    url: "https://www.coinapi.io",
    docs: "https://docs.coinapi.io/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Arbitrage Agent", "Trend Agent", "ML Agent"],
  },
  {
    id: 82,
    name: "BitcoinAverage",
    category: "Cryptocurrency",
    description: "OHLC and volume-weighted price data",
    auth: "apiKey",
    url: "https://bitcoinaverage.com",
    docs: "https://apiv2.bitcoinaverage.com/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Momentum Agent"],
  },
  {
    id: 83,
    name: "Coinlib",
    category: "Cryptocurrency",
    description: "Cryptocurrency prices and portfolio tracking",
    auth: "apiKey",
    url: "https://coinlib.io",
    docs: "https://coinlib.io/apidocs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Portfolio Manager", "Trend Agent"],
  },
  {
    id: 84,
    name: "NiceHash",
    category: "Cryptocurrency",
    description: "Cryptocurrency mining marketplace",
    auth: "apiKey",
    url: "https://www.nicehash.com",
    docs: "https://docs.nicehash.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 85,
    name: "ZMOK",
    category: "Cryptocurrency",
    description: "Ethereum JSON-RPC node access",
    auth: "apiKey",
    url: "https://zmok.io",
    docs: "https://zmok.io/docs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["On-Chain Agent", "DeFi Agent"],
  },
  {
    id: 86,
    name: "Localbitcoins",
    category: "Cryptocurrency",
    description: "Peer-to-peer Bitcoin trading",
    auth: "apiKey",
    url: "https://localbitcoins.com",
    docs: "https://localbitcoins.com/api-docs/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 87,
    name: "CoinRanking",
    category: "Cryptocurrency",
    description: "Cryptocurrency market data and rankings",
    auth: "apiKey",
    url: "https://coinranking.com",
    docs: "https://developers.coinranking.com/api",
    status: "needs_key",
    priority: "high",
    usedBy: ["Trend Agent", "Momentum Agent", "Research Agent"],
  },
  {
    id: 88,
    name: "Bitmex",
    category: "Cryptocurrency",
    description: "Crypto derivatives and perpetual contracts",
    auth: "apiKey",
    url: "https://www.bitmex.com",
    docs: "https://www.bitmex.com/api/explorer/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 89,
    name: "Poloniex",
    category: "Cryptocurrency",
    description: "Cryptocurrency exchange platform",
    auth: "apiKey",
    url: "https://poloniex.com",
    docs: "https://docs.poloniex.com/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 90,
    name: "Huobi",
    category: "Cryptocurrency",
    description: "Major global cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.huobi.com",
    docs: "https://huobiapi.github.io/docs/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 91,
    name: "CryptoCompare (Crypto)",
    category: "Cryptocurrency",
    description: "Cryptocurrency comparison and analytics",
    auth: "apiKey",
    url: "https://www.cryptocompare.com",
    docs: "https://min-api.cryptocompare.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Momentum Agent"],
  },
  {
    id: 92,
    name: "VALR",
    category: "Cryptocurrency",
    description: "South African cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.valr.com",
    docs: "https://docs.valr.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 93,
    name: "OKEx",
    category: "Cryptocurrency",
    description: "Major crypto exchange with derivatives",
    auth: "apiKey",
    url: "https://www.okx.com",
    docs: "https://www.okx.com/docs-v5/en/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 94,
    name: "KuCoin",
    category: "Cryptocurrency",
    description: "Global cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.kucoin.com",
    docs: "https://docs.kucoin.com/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 95,
    name: "Bybit",
    category: "Cryptocurrency",
    description: "Algorithmic trading and derivatives",
    auth: "apiKey",
    url: "https://www.bybit.com",
    docs: "https://bybit-exchange.github.io/docs/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 96,
    name: "Blockchain API",
    category: "Cryptocurrency",
    description: "Bitcoin wallet and transaction data",
    auth: "apiKey",
    url: "https://www.blockchain.com",
    docs: "https://www.blockchain.com/api",
    status: "needs_key",
    priority: "medium",
    usedBy: ["On-Chain Agent", "Research Agent"],
  },
  {
    id: 97,
    name: "CoinRanking (Live)",
    category: "Cryptocurrency",
    description: "Live cryptocurrency price data",
    auth: "apiKey",
    url: "https://coinranking.com",
    docs: "https://developers.coinranking.com/api",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Momentum Agent"],
  },
  {
    id: 98,
    name: "Technical Analysis",
    category: "Cryptocurrency",
    description: "Technical analysis indicators and signals",
    auth: "apiKey",
    url: "https://technical-analysis-api.com",
    docs: "https://technical-analysis-api.com/docs",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "ML Agent", "Risk Manager"],
  },
  {
    id: 99,
    name: "BtcTurk",
    category: "Cryptocurrency",
    description: "Turkish cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.btcturk.com",
    docs: "https://docs.btcturk.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 100,
    name: "BlockFacts",
    category: "Cryptocurrency",
    description: "Compliance-grade crypto market data",
    auth: "apiKey",
    url: "https://blockfacts.io",
    docs: "https://docs.blockfacts.io/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Risk Manager", "Research Agent"],
  },
  {
    id: 101,
    name: "Cryptonator",
    category: "Cryptocurrency",
    description: "Cryptocurrency exchange rate data",
    auth: "No",
    url: "https://www.cryptonator.com",
    docs: "https://www.cryptonator.com/api",
    status: "connected",
    priority: "medium",
    usedBy: ["Arbitrage Agent", "Trend Agent"],
  },
  {
    id: 102,
    name: "Solana JSON RPC",
    category: "Cryptocurrency",
    description: "Solana blockchain node access",
    auth: "No",
    url: "https://solana.com",
    docs: "https://docs.solana.com/developing/clients/jsonrpc-api",
    status: "connected",
    priority: "high",
    usedBy: ["On-Chain Agent", "DeFi Agent"],
  },
  {
    id: 103,
    name: "Messari",
    category: "Cryptocurrency",
    description: "Crypto research data and market intelligence",
    auth: "apiKey",
    url: "https://messari.io",
    docs: "https://messari.io/api/docs",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Research Agent", "ML Agent", "Macro Analyst", "Risk Manager"],
  },
  {
    id: 104,
    name: "Pocket Network",
    category: "Cryptocurrency",
    description: "Multi-chain decentralized relay network",
    auth: "apiKey",
    url: "https://www.pokt.network",
    docs: "https://docs.pokt.network/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["On-Chain Agent", "DeFi Agent"],
  },
  {
    id: 105,
    name: "CoinGecko",
    category: "Cryptocurrency",
    description: "Comprehensive crypto data — prices, volume, market cap",
    auth: "apiKey",
    url: "https://www.coingecko.com",
    docs: "https://www.coingecko.com/en/api/documentation",
    status: "connected",
    priority: "critical",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent", "Portfolio Manager", "ML Agent"],
  },
  {
    id: 106,
    name: "Alchemy Ethereum",
    category: "Cryptocurrency",
    description: "Ethereum node infrastructure and APIs",
    auth: "apiKey",
    url: "https://www.alchemy.com",
    docs: "https://docs.alchemy.com/",
    status: "needs_key",
    priority: "high",
    usedBy: ["On-Chain Agent", "DeFi Agent"],
  },
  {
    id: 107,
    name: "Livecoin",
    category: "Cryptocurrency",
    description: "Cryptocurrency exchange",
    auth: "apiKey",
    url: "https://www.livecoin.net",
    docs: "https://www.livecoin.net/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Arbitrage Agent"],
  },
  {
    id: 108,
    name: "CoinCap",
    category: "Cryptocurrency",
    description: "Real-time cryptocurrency market prices",
    auth: "No",
    url: "https://coincap.io",
    docs: "https://docs.coincap.io/",
    status: "connected",
    priority: "high",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent"],
  },
  {
    id: 109,
    name: "WorldCoinIndex",
    category: "Cryptocurrency",
    description: "Cryptocurrency price index and data",
    auth: "apiKey",
    url: "https://www.worldcoinindex.com",
    docs: "https://www.worldcoinindex.com/apiservice",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent"],
  },
  {
    id: 110,
    name: "Coinbase Pro",
    category: "Cryptocurrency",
    description: "Advanced cryptocurrency trading platform",
    auth: "apiKey",
    url: "https://pro.coinbase.com",
    docs: "https://docs.cloud.coinbase.com/exchange/reference",
    status: "needs_key",
    priority: "critical",
    usedBy: ["Execution Agent", "Arbitrage Agent", "Cost Agent"],
  },
  {
    id: 111,
    name: "Gates.io",
    category: "Cryptocurrency",
    description: "Cryptocurrency exchange and trading",
    auth: "apiKey",
    url: "https://www.gate.io",
    docs: "https://www.gate.io/docs/developers/apiv4/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 112,
    name: "BitcoinCharts",
    category: "Cryptocurrency",
    description: "Historical Bitcoin market data and charts",
    auth: "No",
    url: "https://bitcoincharts.com",
    docs: "https://bitcoincharts.com/about/markets-api/",
    status: "available",
    priority: "medium",
    usedBy: ["Trend Agent", "ML Agent"],
  },
  {
    id: 113,
    name: "INFURA Ethereum",
    category: "Cryptocurrency",
    description: "Ethereum and IPFS node infrastructure",
    auth: "apiKey",
    url: "https://infura.io",
    docs: "https://docs.infura.io/",
    status: "needs_key",
    priority: "high",
    usedBy: ["On-Chain Agent", "DeFi Agent"],
  },
  {
    id: 114,
    name: "CryptoMarket",
    category: "Cryptocurrency",
    description: "Cryptocurrency trading platform",
    auth: "apiKey",
    url: "https://www.cryptomkt.com",
    docs: "https://api.exchange.cryptomkt.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 115,
    name: "CoinLayer",
    category: "Cryptocurrency",
    description: "Real-time cryptocurrency exchange rates",
    auth: "apiKey",
    url: "https://coinlayer.com",
    docs: "https://coinlayer.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Arbitrage Agent", "Trend Agent"],
  },
  {
    id: 116,
    name: "dYdX",
    category: "Cryptocurrency",
    description: "Decentralized derivatives exchange",
    auth: "apiKey",
    url: "https://dydx.exchange",
    docs: "https://docs.dydx.exchange/",
    status: "needs_key",
    priority: "high",
    usedBy: ["DeFi Agent", "Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 117,
    name: "Nomics",
    category: "Cryptocurrency",
    description: "Cryptocurrency market data aggregator",
    auth: "apiKey",
    url: "https://nomics.com",
    docs: "https://nomics.com/docs/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Trend Agent", "Research Agent"],
  },
  {
    id: 118,
    name: "Coinpaprika",
    category: "Cryptocurrency",
    description: "Free cryptocurrency market data",
    auth: "No",
    url: "https://coinpaprika.com",
    docs: "https://api.coinpaprika.com/",
    status: "connected",
    priority: "high",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent"],
  },
  {
    id: 119,
    name: "CoinDCX",
    category: "Cryptocurrency",
    description: "Indian cryptocurrency exchange",
    auth: "apiKey",
    url: "https://coindcx.com",
    docs: "https://docs.coindcx.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Execution Agent", "Arbitrage Agent"],
  },
  {
    id: 120,
    name: "Brave NewCoin",
    category: "Cryptocurrency",
    description: "Multi-exchange crypto data aggregation",
    auth: "apiKey",
    url: "https://bravenewcoin.com",
    docs: "https://bravenewcoin.com/developers",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "Trend Agent"],
  },

  // ============================================================
  // DATA ACCESS (IDs 121–167)
  // ============================================================
  {
    id: 121,
    name: "SearchApi",
    category: "Data_Access",
    description: "SERP scraping and search result extraction",
    auth: "apiKey",
    url: "https://www.searchapi.io",
    docs: "https://www.searchapi.io/docs",
    status: "needs_key",
    priority: "high",
    usedBy: ["Research Agent", "News Intelligence Agent"],
  },
  {
    id: 122,
    name: "Open Government Canada",
    category: "Data_Access",
    description: "Canadian government open data",
    auth: "No",
    url: "https://open.canada.ca",
    docs: "https://open.canada.ca/data/en/dataset",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 123,
    name: "Scraper Box",
    category: "Data_Access",
    description: "Web scraping and data extraction",
    auth: "apiKey",
    url: "https://scraperbox.com",
    docs: "https://scraperbox.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent"],
  },
  {
    id: 124,
    name: "US Open Government",
    category: "Data_Access",
    description: "US federal government open data",
    auth: "No",
    url: "https://www.data.gov",
    docs: "https://www.data.gov/developers/apis",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent", "Macro Analyst"],
  },
  {
    id: 125,
    name: "Hunter",
    category: "Data_Access",
    description: "Email address finder and verification",
    auth: "apiKey",
    url: "https://hunter.io",
    docs: "https://hunter.io/api-documentation",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 126,
    name: "Represent Civic",
    category: "Data_Access",
    description: "Canadian civic information and representatives",
    auth: "No",
    url: "https://represent.opennorth.ca",
    docs: "https://represent.opennorth.ca/api/",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 127,
    name: "Original",
    category: "Data_Access",
    description: "NFT creation and management",
    auth: "apiKey",
    url: "https://getoriginal.com",
    docs: "https://docs.getoriginal.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 128,
    name: "Shutterstock",
    category: "Data_Access",
    description: "Stock images, videos, and music",
    auth: "OAuth",
    url: "https://www.shutterstock.com",
    docs: "https://api-reference.shutterstock.com/",
    status: "premium",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 129,
    name: "Domainsdb.info",
    category: "Data_Access",
    description: "Domain name search and registration data",
    auth: "No",
    url: "https://domainsdb.info",
    docs: "https://api.domainsdb.info/",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 130,
    name: "Yelp",
    category: "Data_Access",
    description: "Business search and review data",
    auth: "apiKey",
    url: "https://www.yelp.com",
    docs: "https://docs.developer.yelp.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 131,
    name: "Dataflow Kit",
    category: "Data_Access",
    description: "Web data extraction and scraping",
    auth: "apiKey",
    url: "https://dataflowkit.com",
    docs: "https://dataflowkit.com/doc-api",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent"],
  },
  {
    id: 132,
    name: "Quandl API",
    category: "Data_Access",
    description: "Premium financial and alternative datasets",
    auth: "apiKey",
    url: "https://data.nasdaq.com",
    docs: "https://docs.data.nasdaq.com/",
    status: "needs_key",
    priority: "critical",
    usedBy: ["ML Agent", "Research Agent", "Macro Analyst", "Risk Manager"],
  },
  {
    id: 133,
    name: "Sunrise Sunset",
    category: "Data_Access",
    description: "Sunrise and sunset time data",
    auth: "No",
    url: "https://sunrise-sunset.org",
    docs: "https://sunrise-sunset.org/api",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 134,
    name: "Scraping Dog",
    category: "Data_Access",
    description: "Web scraping API service",
    auth: "apiKey",
    url: "https://www.scrapingdog.com",
    docs: "https://www.scrapingdog.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent"],
  },
  {
    id: 135,
    name: "Veriphone",
    category: "Data_Access",
    description: "Phone number validation and lookup",
    auth: "apiKey",
    url: "https://veriphone.io",
    docs: "https://veriphone.io/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 136,
    name: "PDF Merge",
    category: "Data_Access",
    description: "PDF manipulation tools",
    auth: "No",
    url: "https://www.pdfmerge.com",
    docs: "https://www.pdfmerge.com/api",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 137,
    name: "Diff bot",
    category: "Data_Access",
    description: "AI-powered web data extraction",
    auth: "apiKey",
    url: "https://www.diffbot.com",
    docs: "https://docs.diffbot.com/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent", "News Intelligence Agent"],
  },
  {
    id: 138,
    name: "Sheety",
    category: "Data_Access",
    description: "Google Sheets as a JSON API",
    auth: "OAuth",
    url: "https://sheety.co",
    docs: "https://sheety.co/docs",
    status: "premium",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 139,
    name: "Data USA",
    category: "Data_Access",
    description: "US demographic and economic data",
    auth: "No",
    url: "https://datausa.io",
    docs: "https://datausa.io/about/api/",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent", "Macro Analyst"],
  },
  {
    id: 140,
    name: "IP2WHOIS",
    category: "Data_Access",
    description: "Domain WHOIS information lookup",
    auth: "apiKey",
    url: "https://www.ip2whois.com",
    docs: "https://www.ip2whois.com/developers-api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 141,
    name: "Teleport",
    category: "Data_Access",
    description: "Quality of life data for cities",
    auth: "No",
    url: "https://teleport.org",
    docs: "https://developers.teleport.org/api/",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 142,
    name: "ScrapeOwl",
    category: "Data_Access",
    description: "Web scraping with JavaScript rendering",
    auth: "apiKey",
    url: "https://scrapeowl.com",
    docs: "https://scrapeowl.com/docs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent"],
  },
  {
    id: 143,
    name: "Dictum API",
    category: "Data_Access",
    description: "Famous quotes and sayings",
    auth: "No",
    url: "https://dictum.dev",
    docs: "https://dictum.dev/api",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 144,
    name: "Australian Open Gov",
    category: "Data_Access",
    description: "Australian government open data",
    auth: "No",
    url: "https://data.gov.au",
    docs: "https://data.gov.au/data/api",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 145,
    name: "Holiday Oracle",
    category: "Data_Access",
    description: "Holiday and observance data worldwide",
    auth: "apiKey",
    url: "https://holidayoracle.io",
    docs: "https://holidayoracle.io/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 146,
    name: "EAN-Search",
    category: "Data_Access",
    description: "International barcode lookup",
    auth: "apiKey",
    url: "https://www.ean-search.org",
    docs: "https://www.ean-search.org/ean-database-api.html",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 147,
    name: "Verimail",
    category: "Data_Access",
    description: "Email address verification",
    auth: "apiKey",
    url: "https://verimail.io",
    docs: "https://verimail.io/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 148,
    name: "UPC database",
    category: "Data_Access",
    description: "Product barcode data lookup",
    auth: "apiKey",
    url: "https://upcdatabase.org",
    docs: "https://upcdatabase.org/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 149,
    name: "Numlookupapi",
    category: "Data_Access",
    description: "Phone number lookup and validation",
    auth: "apiKey",
    url: "https://numlookupapi.com",
    docs: "https://numlookupapi.com/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 150,
    name: "Lingvanex",
    category: "Data_Access",
    description: "Machine translation service",
    auth: "apiKey",
    url: "https://lingvanex.com",
    docs: "https://docs.lingvanex.com/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent", "News Intelligence Agent"],
  },
  {
    id: 151,
    name: "Colorado Data Engine",
    category: "Data_Access",
    description: "Colorado state local data",
    auth: "No",
    url: "https://data.colorado.gov",
    docs: "https://data.colorado.gov/developers",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 152,
    name: "Zenserp",
    category: "Data_Access",
    description: "Search engine results page API",
    auth: "apiKey",
    url: "https://zenserp.com",
    docs: "https://zenserp.com/docs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "News Intelligence Agent"],
  },
  {
    id: 153,
    name: "Open Gov India",
    category: "Data_Access",
    description: "Indian government open data",
    auth: "apiKey",
    url: "https://data.gov.in",
    docs: "https://data.gov.in/help/apis",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 154,
    name: "Dronestream",
    category: "Data_Access",
    description: "Drone strike and incident data",
    auth: "No",
    url: "https://dronestre.am",
    docs: "https://dronestre.am/api",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 155,
    name: "Barcode APIs",
    category: "Data_Access",
    description: "Barcode generation and lookup",
    auth: "apiKey",
    url: "https://www.barcodelookup.com",
    docs: "https://www.barcodelookup.com/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 156,
    name: "Medium",
    category: "Data_Access",
    description: "Medium RSS feed to JSON conversion",
    auth: "No",
    url: "https://medium.com",
    docs: "https://github.com/Medium/medium-api-docs",
    status: "available",
    priority: "medium",
    usedBy: ["News Intelligence Agent", "Research Agent"],
  },
  {
    id: 157,
    name: "WebScraping.AI",
    category: "Data_Access",
    description: "AI-powered web scraping and extraction",
    auth: "apiKey",
    url: "https://webscraping.ai",
    docs: "https://docs.webscraping.ai/",
    status: "needs_key",
    priority: "high",
    usedBy: ["Research Agent", "ML Agent", "News Intelligence Agent"],
  },
  {
    id: 158,
    name: "ScrapingBee",
    category: "Data_Access",
    description: "Web scraping API with proxy rotation",
    auth: "apiKey",
    url: "https://www.scrapingbee.com",
    docs: "https://www.scrapingbee.com/documentation/",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent"],
  },
  {
    id: 159,
    name: "Zenscrape",
    category: "Data_Access",
    description: "Web scraping and data extraction",
    auth: "apiKey",
    url: "https://zenscrape.com",
    docs: "https://zenscrape.com/documentation",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "ML Agent"],
  },
  {
    id: 160,
    name: "Colorado Info Marketplace",
    category: "Data_Access",
    description: "Colorado state data marketplace",
    auth: "No",
    url: "https://data.colorado.gov",
    docs: "https://data.colorado.gov/",
    status: "available",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 161,
    name: "Libraries.io",
    category: "Data_Access",
    description: "Open source software package data",
    auth: "apiKey",
    url: "https://libraries.io",
    docs: "https://libraries.io/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 162,
    name: "Fun Translations",
    category: "Data_Access",
    description: "Fun and novelty text translations",
    auth: "apiKey",
    url: "https://funtranslations.com",
    docs: "https://funtranslations.com/api/",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 163,
    name: "The Social Proxy",
    category: "Data_Access",
    description: "Scraping proxy and data collection",
    auth: "apiKey",
    url: "https://thesocialproxy.com",
    docs: "https://thesocialproxy.com/docs",
    status: "needs_key",
    priority: "medium",
    usedBy: ["Research Agent", "Sentiment Agent"],
  },
  {
    id: 164,
    name: "Skrapp",
    category: "Data_Access",
    description: "Email address finder for leads",
    auth: "apiKey",
    url: "https://skrapp.io",
    docs: "https://skrapp.io/api",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 165,
    name: "BestTime",
    category: "Data_Access",
    description: "Business foot traffic and timing data",
    auth: "apiKey",
    url: "https://besttime.app",
    docs: "https://besttime.app/api/docs",
    status: "needs_key",
    priority: "low",
    usedBy: ["Research Agent"],
  },
  {
    id: 166,
    name: "Coinpaprika (free)",
    category: "Data_Access",
    description: "Free cryptocurrency market data and tickers",
    auth: "No",
    url: "https://coinpaprika.com",
    docs: "https://api.coinpaprika.com/",
    status: "connected",
    priority: "high",
    usedBy: ["Trend Agent", "Momentum Agent", "Arbitrage Agent"],
  },
  {
    id: 167,
    name: "Fear & Greed Index",
    category: "Data_Access",
    description: "Crypto market fear and greed sentiment index",
    auth: "No",
    url: "https://alternative.me",
    docs: "https://alternative.me/crypto/fear-and-greed-index/",
    status: "connected",
    priority: "high",
    usedBy: ["Sentiment Agent", "Risk Manager", "Trend Agent"],
  },
];

// ============================================================
// Helper Functions
// ============================================================

export function getApisByCategory(cat: string): ApiEntry[] {
  return API_REGISTRY.filter((api) => api.category === cat);
}

export function getApisByPriority(priority: string): ApiEntry[] {
  return API_REGISTRY.filter((api) => api.priority === priority);
}

export function getConnectedApis(): ApiEntry[] {
  return API_REGISTRY.filter(
    (api) => api.status === "connected" || isApiConnected(api.id)
  );
}

export function getApisByAgent(agentName: string): ApiEntry[] {
  return API_REGISTRY.filter((api) => api.usedBy.includes(agentName));
}

export function getApiStats(): {
  total: number;
  connected: number;
  needsKey: number;
  premium: number;
  byCategory: Record<string, number>;
} {
  const connected = API_REGISTRY.filter(
    (api) => api.status === "connected" || isApiConnected(api.id)
  ).length;
  const needsKey = API_REGISTRY.filter(
    (api) => api.status === "needs_key" && !isApiConnected(api.id)
  ).length;
  const premium = API_REGISTRY.filter(
    (api) => api.status === "premium"
  ).length;

  const byCategory: Record<string, number> = {};
  for (const api of API_REGISTRY) {
    byCategory[api.category] = (byCategory[api.category] || 0) + 1;
  }

  return {
    total: API_REGISTRY.length,
    connected,
    needsKey,
    premium,
    byCategory,
  };
}

// ============================================================
// API Key Storage
// ============================================================

const API_KEYS_STORAGE = "cryptobot_api_keys_registry";

export interface ApiKeyEntry {
  apiId: number;
  key: string;
  secret?: string;
  addedAt: string;
}

export function loadApiKeyRegistry(): ApiKeyEntry[] {
  if (typeof window === "undefined") return [];
  try {
    const raw = localStorage.getItem(API_KEYS_STORAGE);
    if (!raw) return [];
    return JSON.parse(raw) as ApiKeyEntry[];
  } catch {
    return [];
  }
}

export function saveApiKeyEntry(entry: ApiKeyEntry): void {
  if (typeof window === "undefined") return;
  const registry = loadApiKeyRegistry();
  const idx = registry.findIndex((e) => e.apiId === entry.apiId);
  if (idx >= 0) {
    registry[idx] = entry;
  } else {
    registry.push(entry);
  }
  localStorage.setItem(API_KEYS_STORAGE, JSON.stringify(registry));
}

export function removeApiKeyEntry(apiId: number): void {
  if (typeof window === "undefined") return;
  const registry = loadApiKeyRegistry().filter((e) => e.apiId !== apiId);
  localStorage.setItem(API_KEYS_STORAGE, JSON.stringify(registry));
}

export function isApiConnected(apiId: number): boolean {
  const registry = loadApiKeyRegistry();
  return registry.some((e) => e.apiId === apiId);
}
